// <auto-generated />
namespace ProyectoPersonal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seadicionoelcampototaldespachoaPPTO : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seadicionoelcampototaldespachoaPPTO));
        
        string IMigrationMetadata.Id
        {
            get { return "201712051333017_se adiciono el campo totaldespacho a PPTO"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
