// <auto-generated />
namespace ProyectoPersonal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class cambiosenPapelyCatalogo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cambiosenPapelyCatalogo));
        
        string IMigrationMetadata.Id
        {
            get { return "201711281611189_cambios en Papel y Catalogo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
