// <auto-generated />
namespace ProyectoPersonal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class seadicionoelcampocantidadpres_subPRoceso : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(seadicionoelcampocantidadpres_subPRoceso));
        
        string IMigrationMetadata.Id
        {
            get { return "201712051300534_se adiciono el campo cantidad pres_subPRoceso"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
