// <auto-generated />
namespace ProyectoPersonal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cambiobasededatosinterioropcionalencuadernacionopcional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cambiobasededatosinterioropcionalencuadernacionopcional));
        
        string IMigrationMetadata.Id
        {
            get { return "201804261904054_Cambio base de datos, interior opcional + encuadernacion opcional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
