// <auto-generated />
namespace ProyectoPersonal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class agregandocomovariablesnormales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(agregandocomovariablesnormales));
        
        string IMigrationMetadata.Id
        {
            get { return "201803072102122_agregando como variables normales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
