// <auto-generated />
namespace ProyectoPersonal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tablasproductosEspeciales_presupuestoseagregocostosfijosyvariables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablasproductosEspeciales_presupuestoseagregocostosfijosyvariables));
        
        string IMigrationMetadata.Id
        {
            get { return "201805091856168_tablas productosEspeciales_presupuesto se agrego costos fijos y variables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
