// <auto-generated />
namespace ProyectoPersonal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TipoCatalogo_PapelparasacarIdsseguncorresponda : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TipoCatalogo_PapelparasacarIdsseguncorresponda));
        
        string IMigrationMetadata.Id
        {
            get { return "201803072023449_TipoCatalogo_Papel para sacar Ids segun corresponda"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
