// <auto-generated />
namespace ProyectoPersonal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class tablapresupuesto5tocolornotmapped : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tablapresupuesto5tocolornotmapped));
        
        string IMigrationMetadata.Id
        {
            get { return "201805092035257_tabla presupuesto 5to color not mapped"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
