// <auto-generated />
namespace SolicitudCotizador.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BasedeDatosInicial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BasedeDatosInicial));
        
        string IMigrationMetadata.Id
        {
            get { return "201710312053169_Base de Datos Inicial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
