// <auto-generated />
namespace SolicitudCotizador.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CambiosenColores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CambiosenColores));
        
        string IMigrationMetadata.Id
        {
            get { return "201711031423299_Cambios en Colores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
